import React, { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import api from "../services/api";

const statuses = ["under_review","additional_information_required","conditionally_approved","agreement_pending","agreement_sent","signed_agreement_submitted","agreement_under_review","active","suspended","rejected","terminated","expired"];

export default function AdminPartnershipReview() {
  const { hotelId } = useParams();
  const [data,setData]=useState(null); const [loading,setLoading]=useState(true); const [message,setMessage]=useState("");
  const [status,setStatus]=useState("under_review"); const [partnerMessage,setPartnerMessage]=useState(""); const [internalNote,setInternalNote]=useState("");
  const load=async()=>{try{setLoading(true);const res=await api.get(`/partnership/admin/${hotelId}`);setData(res.data);setStatus(res.data.hotel?.partnershipStatus || (res.data.hotel?.status === "approved" ? "active_legacy" : "under_review"));setPartnerMessage(res.data.hotel?.compliance?.partnerMessage || "");setInternalNote(res.data.hotel?.compliance?.internalNote || "");}catch(error){setMessage(error.response?.data?.message || "Unable to load partnership record.");}finally{setLoading(false);}};
  useEffect(()=>{load();},[hotelId]);
  const saveStatus=async()=>{try{await api.patch(`/partnership/admin/${hotelId}/status`,{status,partnerMessage,internalNote});setMessage("Partnership status updated.");await load();}catch(error){setMessage(error.response?.data?.message || "Unable to update status.");}};
  const reviewDoc=async(id,next)=>{const note=window.prompt(`Review note for ${next}:`,"") ?? "";try{await api.patch(`/partnership/admin/documents/${id}`,{status:next,reviewNote:note});await load();}catch(error){setMessage(error.response?.data?.message || "Unable to review document.");}};
  const downloadDocument=async(doc)=>{try{const response=await api.get(`/partnership/documents/${doc._id}/download`,{responseType:"blob"});const url=URL.createObjectURL(response.data);const anchor=document.createElement("a");anchor.href=url;anchor.download=doc.originalName||"document";document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url);}catch(error){setMessage(error.response?.data?.message||"Document download failed.");}};
  if(loading)return <main className="min-h-screen pt-24 px-6"><div className="card-ambient p-8 animate-pulse">Loading partner record...</div></main>;
  const hotel=data?.hotel;if(!hotel)return <main className="min-h-screen pt-24 px-6">{message || "Hotel not found."}</main>;
  return <main className="min-h-screen bg-surface-cream pt-24 pb-16 px-margin-mobile md:px-margin-desktop"><div className="max-w-6xl mx-auto"><Link to="/admin/hotels" className="text-secondary">← Hotel Applications</Link><div className="mt-4 mb-6"><span className="badge-gold">Compliance Review</span><h1 className="font-headline-lg text-text-deep-green mt-2">{hotel.hotelName}</h1><p className="text-on-surface-variant">{hotel.application?.applicationNumber || hotel._id} · {hotel.owner?.email || hotel.email}</p></div>{message&&<div className="mb-4 card-ambient p-4">{message}</div>}<div className="grid lg:grid-cols-[1fr_.9fr] gap-5"><section className="card-ambient p-5 md:p-6"><h2 className="font-headline-md text-text-deep-green">Documents</h2><div className="mt-4 space-y-3">{(data.documents||[]).map(doc=><div className="df-document-row" key={doc._id}><div><strong>{doc.documentType.replaceAll("_"," ")}</strong><small>{doc.originalName} · {Math.ceil(doc.size/1024)} KB</small></div><div><span className="status-pill bg-surface-container-low">{doc.status}</span><button type="button" className="text-secondary hover:underline" onClick={()=>downloadDocument(doc)}>Open</button></div><div className="flex gap-2"><button className="btn-outline" onClick={()=>reviewDoc(doc._id,"verified")}>Verify</button><button className="btn-outline" onClick={()=>reviewDoc(doc._id,"rejected")}>Reject</button></div>{doc.reviewNote&&<p>{doc.reviewNote}</p>}</div>)}{!data.documents?.length&&<p className="text-on-surface-variant py-5">No documents submitted.</p>}</div></section><section className="card-ambient p-5 md:p-6"><h2 className="font-headline-md text-text-deep-green">Partnership decision</h2><label className="block mt-4"><span className="font-label-sm">Status</span><select className="form-select w-full mt-1" value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(item=><option key={item} value={item}>{item.replaceAll("_"," ")}</option>)}</select></label><label className="block mt-4"><span className="font-label-sm">Partner message</span><textarea className="form-input w-full mt-1 min-h-[110px]" value={partnerMessage} onChange={e=>setPartnerMessage(e.target.value)} /></label><label className="block mt-4"><span className="font-label-sm">Internal Admin note — never shown to hotel</span><textarea className="form-input w-full mt-1 min-h-[110px]" value={internalNote} onChange={e=>setInternalNote(e.target.value)} /></label><button className="btn-primary w-full mt-4" onClick={saveStatus}>Save decision</button><p className="text-xs text-on-surface-variant mt-3">Activation is Admin-authorized server-side. A hotel cannot activate itself by changing frontend requests.</p></section></div></div></main>;
}
